import os

bs = '\\'
lt = '<'
gt = '>'
q = "'"

# Create all folders
folders = [
    'lib' + bs + 'screens' + bs + 'ai_advisor' + bs + 'widgets',
    'lib' + bs + 'screens' + bs + 'crop_calendar',
    'lib' + bs + 'screens' + bs + 'reports',
]
for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print('Created: ' + folder)

def write(path, lines):
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print('Written: ' + path)

# ── risk_meter.dart ───────────────────────────────────────────────────
write('lib' + bs + 'screens' + bs + 'ai_advisor' + bs + 'widgets' + bs + 'risk_meter.dart', [
    "import 'dart:math';",
    "import 'package:flutter/material.dart';",
    "import 'package:cropsense/core/utils.dart';",
    "class RiskMeterWidget extends StatelessWidget {",
    "  final double riskScore;",
    "  const RiskMeterWidget({super.key, required this.riskScore});",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Column(children: [",
    "      CustomPaint(size: const Size(180, 100), painter: _GaugePainter(riskScore: riskScore)),",
    "      const SizedBox(height: 8),",
    "      Text('Risk Score: ' + riskScore.toStringAsFixed(0) + '/100',",
    "          style: TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: riskScoreColor(riskScore))),",
    "    ]);",
    "  }",
    "}",
    "class _GaugePainter extends CustomPainter {",
    "  final double riskScore;",
    "  _GaugePainter({required this.riskScore});",
    "  @override",
    "  void paint(Canvas canvas, Size size) {",
    "    final cx = size.width / 2; final cy = size.height;",
    "    final radius = size.width / 2 - 10;",
    "    final rect = Rect.fromCircle(center: Offset(cx, cy), radius: radius);",
    "    canvas.drawArc(rect, pi, pi, false, Paint()..color = const Color(0xFFEEEEEE)..style = PaintingStyle.stroke..strokeWidth = 16..strokeCap = StrokeCap.round);",
    "    final sweep = pi * (riskScore / 100);",
    "    canvas.drawArc(rect, pi, sweep, false, Paint()",
    "      ..shader = SweepGradient(startAngle: pi, endAngle: pi + sweep,",
    "        colors: const [Color(0xFF1B5E20), Color(0xFF8BC34A), Color(0xFFFF8F00), Color(0xFFE65100), Color(0xFFB71C1C)],",
    "      ).createShader(rect)..style = PaintingStyle.stroke..strokeWidth = 16..strokeCap = StrokeCap.round);",
    "    final angle = pi + (pi * riskScore / 100);",
    "    canvas.drawLine(Offset(cx, cy), Offset(cx + (radius-8)*cos(angle), cy + (radius-8)*sin(angle)),",
    "      Paint()..color = const Color(0xFF1A1A1A)..strokeWidth = 2.5..strokeCap = StrokeCap.round);",
    "    canvas.drawCircle(Offset(cx, cy), 5, Paint()..color = const Color(0xFF1A1A1A));",
    "  }",
    "  @override bool shouldRepaint(_GaugePainter old) => old.riskScore != riskScore;",
    "}",
])

# ── symptom_selector.dart ─────────────────────────────────────────────
write('lib' + bs + 'screens' + bs + 'ai_advisor' + bs + 'widgets' + bs + 'symptom_selector.dart', [
    "import 'package:flutter/material.dart';",
    "import 'package:cropsense/core/constants.dart';",
    "import 'package:cropsense/core/theme.dart';",
    "class SymptomSelector extends StatelessWidget {",
    "  final List<String> selected;",
    "  final ValueChanged<String> onToggle;",
    "  const SymptomSelector({super.key, required this.selected, required this.onToggle});",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "      Text('Observed Symptoms', style: AppTextStyles.headingSmall),",
    "      const SizedBox(height: 8),",
    "      Text('Select all that apply', style: AppTextStyles.bodySmall),",
    "      const SizedBox(height: 12),",
    "      Wrap(spacing: 8, runSpacing: 8, children: AppSymptoms.all.map((s) {",
    "        final sel = selected.contains(s['id']);",
    "        return GestureDetector(",
    "          onTap: () => onToggle(s['id'] as String),",
    "          child: AnimatedContainer(",
    "            duration: const Duration(milliseconds: 200),",
    "            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),",
    "            decoration: BoxDecoration(",
    "              color: sel ? AppColors.deepGreen : AppColors.grey100,",
    "              borderRadius: BorderRadius.circular(10),",
    "              border: Border.all(color: sel ? AppColors.deepGreen : AppColors.grey200, width: 1.5),",
    "            ),",
    "            child: Row(mainAxisSize: MainAxisSize.min, children: [",
    "              Icon(sel ? Icons.check_circle_rounded : Icons.circle_outlined,",
    "                  size: 16, color: sel ? Colors.white : AppColors.grey600),",
    "              const SizedBox(width: 6),",
    "              Text(s['label'] as String,",
    "                  style: TextStyle(fontSize: 13, fontWeight: FontWeight.w500,",
    "                      color: sel ? Colors.white : AppColors.darkText)),",
    "            ]),",
    "          ),",
    "        );",
    "      }).toList()),",
    "    ]);",
    "  }",
    "}",
])

# ── medicine_card.dart ────────────────────────────────────────────────
write('lib' + bs + 'screens' + bs + 'ai_advisor' + bs + 'widgets' + bs + 'medicine_card.dart', [
    "import 'package:flutter/material.dart';",
    "import 'package:cropsense/core/theme.dart';",
    "import 'package:cropsense/core/utils.dart';",
    "class MedicineCard extends StatelessWidget {",
    "  final String name, type, dose, urgency, purpose, whereToBuy;",
    "  final double pricePerAcre;",
    "  const MedicineCard({super.key, required this.name, required this.type,",
    "    required this.dose, required this.pricePerAcre, required this.urgency,",
    "    required this.purpose, required this.whereToBuy});",
    "  Color get _uc { switch (urgency) {",
    "    case 'immediate': return AppColors.burntOrange;",
    "    case 'within_week': return AppColors.amber;",
    "    default: return AppColors.limeGreen; } }",
    "  String get _ul { switch (urgency) {",
    "    case 'immediate': return 'Immediately';",
    "    case 'within_week': return 'Within a Week';",
    "    default: return 'Preventive'; } }",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Container(",
    "      margin: const EdgeInsets.only(bottom: 12),",
    "      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
    "        border: Border.all(color: _uc.withValues(alpha: 0.3)), boxShadow: AppShadows.card),",
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        Container(",
    "          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),",
    "          decoration: BoxDecoration(color: _uc.withValues(alpha: 0.08),",
    "              borderRadius: const BorderRadius.vertical(top: Radius.circular(12))),",
    "          child: Row(children: [",
    "            Icon(Icons.medication_rounded, color: _uc, size: 20),",
    "            const SizedBox(width: 8),",
    "            Expanded(child: Text(name, style: AppTextStyles.headingSmall.copyWith(fontSize: 14))),",
    "            Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),",
    "              decoration: BoxDecoration(color: _uc, borderRadius: BorderRadius.circular(100)),",
    "              child: Text(_ul, style: const TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.w700))),",
    "          ]),",
    "        ),",
    "        Padding(padding: const EdgeInsets.all(12), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "          _r(Icons.science_rounded, 'Dose', dose),",
    "          const SizedBox(height: 6),",
    "          _r(Icons.currency_rupee_rounded, 'Cost/acre', formatPKR(pricePerAcre)),",
    "          const SizedBox(height: 6),",
    "          _r(Icons.info_outline_rounded, 'Treats', purpose),",
    "          const SizedBox(height: 6),",
    "          _r(Icons.store_rounded, 'Buy at', whereToBuy),",
    "        ])),",
    "      ]),",
    "    );",
    "  }",
    "  Widget _r(IconData icon, String label, String value) {",
    "    return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "      Icon(icon, size: 14, color: AppColors.grey600),",
    "      const SizedBox(width: 6),",
    "      Text(label + ': ', style: AppTextStyles.bodySmall.copyWith(fontWeight: FontWeight.w600)),",
    "      Expanded(child: Text(value, style: AppTextStyles.bodySmall)),",
    "    ]);",
    "  }",
    "}",
])

# ── advice_result_panel.dart ──────────────────────────────────────────
write('lib' + bs + 'screens' + bs + 'ai_advisor' + bs + 'widgets' + bs + 'advice_result_panel.dart', [
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_animate/flutter_animate.dart';",
    "import 'package:cropsense/core/theme.dart';",
    "import 'package:cropsense/core/utils.dart';",
    "import 'package:cropsense/data/models/ai_advice.dart';",
    "import 'package:cropsense/screens/ai_advisor/widgets/medicine_card.dart';",
    "class AdviceResultPanel extends StatelessWidget {",
    "  final AIAdvice advice;",
    "  const AdviceResultPanel({super.key, required this.advice});",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return SingleChildScrollView(",
    "      padding: const EdgeInsets.all(16),",
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        _alert(), const SizedBox(height: 16),",
    "        _diagnosis(), const SizedBox(height: 16),",
    "        _steps(), const SizedBox(height: 16),",
    "        if (advice.medicines.isNotEmpty) ...[",
    "          Text('Recommended Products', style: AppTextStyles.headingSmall),",
    "          const SizedBox(height: 8),",
    "          ...advice.medicines.map((m) => MedicineCard(name: m.name, type: m.type.name,",
    "            dose: m.dose, pricePerAcre: m.pricePerAcrePkr, urgency: m.urgency.name,",
    "            purpose: m.purpose, whereToBuy: m.whereToBuy)),",
    "          const SizedBox(height: 16),",
    "        ],",
    "        _costCard(), const SizedBox(height: 16),",
    "        _twoCards(),",
    "      ]),",
    "    ).animate().fadeIn(duration: 400.ms).slideY(begin: 0.1, end: 0);",
    "  }",
    "  Widget _alert() {",
    "    return Container(width: double.infinity, padding: const EdgeInsets.all(14),",
    "      decoration: BoxDecoration(color: const Color(0xFFB71C1C).withValues(alpha: 0.08),",
    "        borderRadius: BorderRadius.circular(12),",
    "        border: Border.all(color: const Color(0xFFB71C1C).withValues(alpha: 0.3))),",
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        Row(children: [",
    "          const Icon(Icons.warning_rounded, color: Color(0xFFB71C1C), size: 20),",
    "          const SizedBox(width: 8),",
    "          Expanded(child: Text('Alert', style: AppTextStyles.headingSmall.copyWith(color: const Color(0xFFB71C1C)))),",
    "          Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),",
    "            decoration: BoxDecoration(color: AppColors.limeGreen.withValues(alpha: 0.15), borderRadius: BorderRadius.circular(100)),",
    "            child: Text(advice.confidencePct.toStringAsFixed(0) + '% confidence',",
    "              style: const TextStyle(fontSize: 11, color: AppColors.deepGreen, fontWeight: FontWeight.w700))),",
    "        ]),",
    "        const SizedBox(height: 8),",
    "        Text(advice.alertEnglish, style: AppTextStyles.bodyMedium.copyWith(fontWeight: FontWeight.w600)),",
    "        const SizedBox(height: 6),",
    "        Container(padding: const EdgeInsets.all(8),",
    "          decoration: BoxDecoration(color: AppColors.deepGreen.withValues(alpha: 0.06), borderRadius: BorderRadius.circular(6)),",
    "          child: Text(advice.alertUrdu, style: AppTextStyles.urduBody.copyWith(fontSize: 14))),",
    "      ]),",
    "    );",
    "  }",
    "  Widget _diagnosis() {",
    "    return Container(padding: const EdgeInsets.all(14),",
    "      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
    "        border: Border.all(color: AppColors.grey200), boxShadow: AppShadows.card),",
    "      child: Row(children: [",
    "        Container(padding: const EdgeInsets.all(10),",
    "          decoration: BoxDecoration(color: AppColors.skyBlue.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(10)),",
    "          child: const Icon(Icons.biotech_rounded, color: AppColors.skyBlue, size: 24)),",
    "        const SizedBox(width: 12),",
    "        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "          Text('Diagnosis', style: AppTextStyles.label),",
    "          const SizedBox(height: 2),",
    "          Text(advice.diagnosis, style: AppTextStyles.bodyMedium.copyWith(fontWeight: FontWeight.w700)),",
    "        ])),",
    "      ]),",
    "    );",
    "  }",
    "  Widget _steps() {",
    "    return Container(padding: const EdgeInsets.all(14),",
    "      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
    "        border: Border.all(color: AppColors.grey200), boxShadow: AppShadows.card),",
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        Row(children: [const Icon(Icons.checklist_rounded, color: AppColors.deepGreen, size: 20),",
    "          const SizedBox(width: 8), Text('Action Steps', style: AppTextStyles.headingSmall)]),",
    "        const SizedBox(height: 12),",
    "        ...advice.actionSteps.map((step) => Padding(",
    "          padding: const EdgeInsets.only(bottom: 8),",
    "          child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "            Container(width: 20, height: 20,",
    "              decoration: BoxDecoration(color: AppColors.deepGreen, borderRadius: BorderRadius.circular(100)),",
    "              child: const Icon(Icons.check, color: Colors.white, size: 12)),",
    "            const SizedBox(width: 10),",
    "            Expanded(child: Text(step, style: AppTextStyles.bodyMedium)),",
    "          ]),",
    "        )),",
    "      ]),",
    "    );",
    "  }",
    "  Widget _costCard() {",
    "    return Container(padding: const EdgeInsets.all(14),",
    "      decoration: BoxDecoration(color: AppColors.deepGreen, borderRadius: BorderRadius.circular(12)),",
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        Text('Cost and ROI', style: AppTextStyles.headingSmall.copyWith(color: Colors.white)),",
    "        const SizedBox(height: 12),",
    "        Row(children: [",
    "          _chip('Per Acre', formatPKR(advice.totalCostPerAcrePkr), Icons.grass_rounded),",
    "          const SizedBox(width: 8),",
    "          _chip('Total Farm', formatPKR(advice.totalCostForFarmPkr), Icons.agriculture_rounded),",
    "          const SizedBox(width: 8),",
    "          _chip('Yield Boost', '+' + advice.expectedYieldIncreasePct.toStringAsFixed(0) + '%', Icons.trending_up_rounded),",
    "        ]),",
    "        const SizedBox(height: 10),",
    "        Container(padding: const EdgeInsets.all(10),",
    "          decoration: BoxDecoration(color: Colors.white.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(8)),",
    "          child: Row(children: [",
    "            const Icon(Icons.lightbulb_rounded, color: Color(0xFF8BC34A), size: 16),",
    "            const SizedBox(width: 8),",
    "            Expanded(child: Text(advice.roiNote, style: const TextStyle(color: Colors.white, fontSize: 12))),",
    "          ])),",
    "      ]),",
    "    );",
    "  }",
    "  Widget _chip(String label, String value, IconData icon) {",
    "    return Expanded(child: Container(padding: const EdgeInsets.all(10),",
    "      decoration: BoxDecoration(color: Colors.white.withValues(alpha: 0.12), borderRadius: BorderRadius.circular(8)),",
    "      child: Column(children: [",
    "        Icon(icon, color: Colors.white70, size: 16),",
    "        const SizedBox(height: 4),",
    "        Text(value, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 13)),",
    "        Text(label, style: const TextStyle(color: Colors.white60, fontSize: 10)),",
    "      ]),",
    "    ));",
    "  }",
    "  Widget _twoCards() {",
    "    return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "      Expanded(child: _info(Icons.water_drop_rounded, 'Irrigation', advice.irrigationAdvice, AppColors.skyBlue)),",
    "      const SizedBox(width: 12),",
    "      Expanded(child: _info(Icons.eco_rounded, 'Fertilizer', advice.fertilizerAdvice, AppColors.limeGreen)),",
    "    ]);",
    "  }",
    "  Widget _info(IconData icon, String title, String body, Color color) {",
    "    return Container(padding: const EdgeInsets.all(12),",
    "      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
    "        border: Border.all(color: color.withValues(alpha: 0.3)), boxShadow: AppShadows.card),",
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        Row(children: [Icon(icon, color: color, size: 16), const SizedBox(width: 6),",
    "          Text(title, style: AppTextStyles.headingSmall.copyWith(fontSize: 13, color: color))]),",
    "        const SizedBox(height: 8),",
    "        Text(body, style: AppTextStyles.bodySmall),",
    "      ]),",
    "    );",
    "  }",
    "}",
])

# ── ai_advisor_screen.dart ────────────────────────────────────────────
write('lib' + bs + 'screens' + bs + 'ai_advisor' + bs + 'ai_advisor_screen.dart', [
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "import 'package:cropsense/core/constants.dart';",
    "import 'package:cropsense/core/theme.dart';",
    "import 'package:cropsense/providers/ai_advisor_provider.dart';",
    "import 'package:cropsense/screens/ai_advisor/widgets/risk_meter.dart';",
    "import 'package:cropsense/screens/ai_advisor/widgets/symptom_selector.dart';",
    "import 'package:cropsense/screens/ai_advisor/widgets/advice_result_panel.dart';",
    "class AIAdvisorScreen extends ConsumerWidget {",
    "  const AIAdvisorScreen({super.key});",
    "  @override",
    "  Widget build(BuildContext context, WidgetRef ref) {",
    "    final width = MediaQuery.of(context).size.width;",
    "    final isCompact = width < 800;",
    "    final form = ref.watch(advisorFormProvider);",
    "    final adviceAsync = ref.watch(aiAdviceProvider);",
    "    if (isCompact) {",
    "      return Scaffold(backgroundColor: AppColors.offWhite,",
    "        body: SingleChildScrollView(padding: const EdgeInsets.all(16),",
    "          child: Column(children: [",
    "            _header(),",
    "            const SizedBox(height: 16),",
    "            _form(context, ref, form),",
    "            const SizedBox(height: 16),",
    "            adviceAsync.when(",
    "              data: (a) => a != null ? AdviceResultPanel(advice: a) : const SizedBox.shrink(),",
    "              loading: () => const CircularProgressIndicator(color: AppColors.deepGreen),",
    "              error: (e, _) => Text(e.toString()),",
    "            ),",
    "          ]),",
    "        ),",
    "      );",
    "    }",
    "    return Scaffold(backgroundColor: AppColors.offWhite,",
    "      body: Column(children: [",
    "        _header(),",
    "        Expanded(child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "          SizedBox(width: 420, child: SingleChildScrollView(",
    "            padding: const EdgeInsets.all(20), child: _form(context, ref, form))),",
    "          Container(width: 1, color: AppColors.grey200),",
    "          Expanded(child: adviceAsync.when(",
    "            data: (a) => a != null ? AdviceResultPanel(advice: a) : _empty(),",
    "            loading: () => const Center(child: CircularProgressIndicator(color: AppColors.deepGreen)),",
    "            error: (e, _) => Center(child: Text(e.toString())),",
    "          )),",
    "        ])),",
    "      ]),",
    "    );",
    "  }",
    "  Widget _header() {",
    "    return Container(",
    "      padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),",
    "      decoration: BoxDecoration(color: AppColors.cardSurface,",
    "        border: Border(bottom: BorderSide(color: AppColors.grey200))),",
    "      child: Row(children: [",
    "        Container(padding: const EdgeInsets.all(8),",
    "          decoration: BoxDecoration(color: AppColors.amber.withValues(alpha: 0.12), borderRadius: BorderRadius.circular(10)),",
    "          child: const Icon(Icons.psychology_rounded, color: AppColors.amber, size: 24)),",
    "        const SizedBox(width: 12),",
    "        Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "          Text('AI Farm Advisor', style: AppTextStyles.headingMedium),",
    "          Text('Powered by Grok AI - Roman Urdu + English', style: AppTextStyles.bodySmall),",
    "        ]),",
    "      ]),",
    "    );",
    "  }",
    "  Widget _form(BuildContext context, WidgetRef ref, AdvisorFormState form) {",
    "    final n = ref.read(advisorFormProvider.notifier);",
    "    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "      Text('Farm Conditions', style: AppTextStyles.headingSmall),",
    "      const SizedBox(height: 16),",
    "      Row(children: [",
    "        Expanded(child: _dd<String>('District', form.district,",
    "          AppDistricts.all.take(12).map((d) => DropdownMenuItem(value: d['id'], child: Text(d['label']!))).toList(),",
    "          n.setDistrict)),",
    "        const SizedBox(width: 12),",
    "        Expanded(child: _dd<String>('Crop', form.crop,",
    "          AppCrops.all.map((c) => DropdownMenuItem(value: c['id'], child: Text(c['label']!))).toList(),",
    "          n.setCrop)),",
    "      ]),",
    "      const SizedBox(height: 12),",
    "      Row(children: [",
    "        Expanded(child: _dd<String>('Season', form.season,",
    "          ['Rabi', 'Kharif'].map((s) => DropdownMenuItem(value: s, child: Text(s))).toList(),",
    "          n.setSeason)),",
    "        const SizedBox(width: 12),",
    "        Expanded(child: _sl('Farm Size', form.farmSizeAcres, 1, 100, ' acres', n.setFarmSize)),",
    "      ]),",
    "      const SizedBox(height: 16),",
    "      Text('Field Readings', style: AppTextStyles.headingSmall),",
    "      const SizedBox(height: 12),",
    "      _sl('NDVI', form.ndvi, 0.0, 1.0, '', n.setNdvi, dec: 2),",
    "      _sl('Rainfall', form.rainfallMm, 0, 500, ' mm', n.setRainfall),",
    "      _sl('Max Temp', form.tempMaxC, 20, 50, ' C', n.setTempMax),",
    "      _sl('Soil Moisture', form.soilMoisturePct, 10, 80, '%', n.setSoilMoisture),",
    "      _sl('Water Table', form.waterTableM, 1, 20, ' m', n.setWaterTable),",
    "      const SizedBox(height: 16),",
    "      Consumer(builder: (ctx, ref, _) {",
    "        final f = ref.watch(advisorFormProvider);",
    "        return SymptomSelector(selected: f.selectedSymptoms,",
    "          onToggle: ref.read(advisorFormProvider.notifier).toggleSymptom);",
    "      }),",
    "      const SizedBox(height: 20),",
    "      Center(child: RiskMeterWidget(riskScore: _risk(form))),",
    "      const SizedBox(height: 20),",
    "      SizedBox(width: double.infinity, child: Consumer(builder: (ctx, ref, _) {",
    "        final busy = ref.watch(aiAdviceProvider) is AsyncLoading;",
    "        return ElevatedButton.icon(",
    "          onPressed: busy ? null : () => ref.read(aiAdviceProvider.notifier).analyze(),",
    "          icon: busy ? const SizedBox(width: 18, height: 18,",
    "            child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))",
    "            : const Icon(Icons.psychology_rounded),",
    "          label: Text(busy ? 'Analyzing...' : 'Analyze with AI'),",
    "          style: ElevatedButton.styleFrom(backgroundColor: AppColors.amber,",
    "            foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(vertical: 14),",
    "            textStyle: const TextStyle(fontSize: 15, fontWeight: FontWeight.w700)),",
    "        );",
    "      })),",
    "    ]);",
    "  }",
    "  Widget _dd<T>(String label, T value, List<DropdownMenuItem<T>> items, ValueChanged<T> fn) {",
    "    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "      Text(label, style: AppTextStyles.label), const SizedBox(height: 4),",
    "      Container(padding: const EdgeInsets.symmetric(horizontal: 12),",
    "        decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(8),",
    "          border: Border.all(color: AppColors.grey200)),",
    "        child: DropdownButton<T>(value: value, items: items,",
    "          onChanged: (v) => fn(v as T), isExpanded: true,",
    "          underline: const SizedBox.shrink(), style: AppTextStyles.bodyMedium)),",
    "    ]);",
    "  }",
    "  Widget _sl(String label, double value, double min, double max, String unit, ValueChanged<double> fn, {int dec = 0}) {",
    "    final d = dec == 0 ? value.toStringAsFixed(0) : value.toStringAsFixed(dec);",
    "    return Padding(padding: const EdgeInsets.only(bottom: 8), child: Row(children: [",
    "      SizedBox(width: 100, child: Text(label, style: AppTextStyles.bodySmall.copyWith(fontWeight: FontWeight.w600))),",
    "      Expanded(child: SliderTheme(data: const SliderThemeData(trackHeight: 3,",
    "        thumbShape: RoundSliderThumbShape(enabledThumbRadius: 7)),",
    "        child: Slider(value: value, min: min, max: max,",
    "          activeColor: AppColors.deepGreen, inactiveColor: AppColors.grey200, onChanged: fn))),",
    "      SizedBox(width: 70, child: Text(d + unit,",
    "        style: AppTextStyles.bodySmall.copyWith(fontWeight: FontWeight.w700, color: AppColors.deepGreen),",
    "        textAlign: TextAlign.right)),",
    "    ]));",
    "  }",
    "  Widget _empty() {",
    "    return Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [",
    "      Container(padding: const EdgeInsets.all(24),",
    "        decoration: BoxDecoration(color: AppColors.amber.withValues(alpha: 0.1), shape: BoxShape.circle),",
    "        child: const Icon(Icons.psychology_rounded, color: AppColors.amber, size: 48)),",
    "      const SizedBox(height: 20),",
    "      Text('Fill in farm conditions', style: AppTextStyles.headingMedium),",
    "      const SizedBox(height: 8),",
    "      Text('Then tap Analyze with AI', style: AppTextStyles.bodyMedium.copyWith(color: AppColors.grey600),",
    "        textAlign: TextAlign.center),",
    "    ]));",
    "  }",
    "  double _risk(AdvisorFormState form) {",
    "    double s = 0;",
    "    if (form.ndvi < 0.3) s += 30; else if (form.ndvi < 0.5) s += 15;",
    "    if (form.rainfallMm < 50) s += 25; else if (form.rainfallMm < 100) s += 10;",
    "    if (form.tempMaxC > 42) s += 20; else if (form.tempMaxC > 38) s += 10;",
    "    if (form.soilMoisturePct < 20) s += 15;",
    "    if (form.selectedSymptoms.isNotEmpty && !form.selectedSymptoms.contains('no_symptoms')) s += 10;",
    "    return s.clamp(0, 100);",
    "  }",
    "}",
])

# ── crop_calendar_screen.dart ─────────────────────────────────────────
write('lib' + bs + 'screens' + bs + 'crop_calendar' + bs + 'crop_calendar_screen.dart', [
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_animate/flutter_animate.dart';",
    "import 'package:cropsense/core/theme.dart';",
    "import 'package:cropsense/core/constants.dart';",
    "class CropCalendarScreen extends StatefulWidget {",
    "  const CropCalendarScreen({super.key});",
    "  @override",
    "  State<CropCalendarScreen> createState() => _State();",
    "}",
    "class _State extends State<CropCalendarScreen> {",
    "  String _crop = 'wheat';",
    "  final _data = {",
    "    'wheat': [",
    "      ['Land Preparation','Oct 1-15','Deep plough 2-3 times. Add DAP 1 bag/acre. Level field for uniform irrigation.','amber',15],",
    "      ['Sowing','Oct 16 - Nov 15','Sow certified seed at 50kg/acre. Row spacing 22cm, depth 5cm. Varieties: Punjab-2011, Faisalabad-2008.','lime',30],",
    "      ['First Irrigation','Nov 20-25','Apply first irrigation 3-4 weeks after sowing. Do not over-irrigate.','blue',5],",
    "      ['Fertilizer','Dec 1-15','Apply 1 bag Urea/acre with 2nd irrigation. Watch for nitrogen deficiency (yellowing).','green',15],",
    "      ['Disease Watch','Jan 1 - Feb 28','Monitor weekly for yellow rust. Spray Topsin-M 70WP at 250g/acre if rust appears.','orange',59],",
    "      ['Heading','Mar 1-20','Critical water stage. Apply 3rd irrigation at heading. Protect from frost.','amber',20],",
    "      ['Grain Filling','Mar 21 - Apr 10','Apply final irrigation. Stop pesticides 3 weeks before harvest.','lime',20],",
    "      ['Harvest','Apr 15-30','Harvest at 12-14% moisture. Expected yield: 2.0-2.8 t/acre.','green',15],",
    "    ],",
    "    'rice': [",
    "      ['Nursery','May 15 - Jun 1','Prepare beds. Soak seeds 24hr. Keep moist but not waterlogged.','lime',17],",
    "      ['Transplanting','Jun 15 - Jul 10','Transplant 30-35 day seedlings. Row spacing 20x15cm. Flood fields 2-3cm.','blue',25],",
    "      ['Water Management','Jul 1 - Aug 15','Apply Urea in 3 splits. Maintain 5-7cm water depth throughout.','blue',45],",
    "      ['Disease Control','Jul 15 - Sep 1','Watch for blast disease. Apply Beam (Tricyclazole) 200g/acre.','orange',47],",
    "      ['Harvest','Sep 15 - Oct 15','Harvest when 80% grains golden. Expected: 1.5-2.2 t/acre.','green',30],",
    "    ],",
    "    'cotton': [",
    "      ['Land Prep','Apr 1-30','Deep plough. Apply FYM 5 tons/acre. Needs well-drained loamy soil.','amber',30],",
    "      ['Sowing','May 1-31','Sow 5kg seed/acre. Row spacing 75cm. Soil temp must be 25C+.','lime',31],",
    "      ['Pest Management','Jun 15 - Sep 30','Scout weekly for whitefly and bollworm. Use Confidor when needed.','orange',107],",
    "      ['Boll Development','Aug 1 - Sep 30','Irrigate every 10 days. Apply SOP at boll formation.','amber',60],",
    "      ['Picking','Sep 15 - Nov 30','First pick when 60% bolls open. Expected: 1.5-2.2 t/acre.','green',76],",
    "    ],",
    "    'sugarcane': [",
    "      ['Planting','Nov 1 - Dec 31','Plant setts in furrows 90cm apart. 7-8 tons setts/acre. Irrigate immediately.','lime',61],",
    "      ['Early Growth','Jan 1 - Mar 31','Germination 3-4 weeks. Apply Atrazine for weeds. First fertilizer at 45 days.','blue',90],",
    "      ['Grand Growth','Apr 1 - Aug 31','Max water demand. Irrigate every 10-15 days. Apply 3 bags Urea total.','green',153],",
    "      ['Harvest','Nov 1 - Jan 31','Stop irrigation 6 weeks before harvest. Brix must be 18%+. Expected: 25-35 t/acre.','amber',92],",
    "    ],",
    "    'maize': [",
    "      ['Sowing','Apr 1-30','Sow hybrid seed 8-10kg/acre. Row spacing 75cm. Soil temp above 15C.','lime',30],",
    "      ['Vegetative','May 1 - Jun 15','Thin at V3 stage. Apply Urea at knee height. Irrigate every 8-10 days.','blue',45],",
    "      ['Tasseling','Jun 16 - Jul 15','Most critical water period. Apply 2nd Urea at tasseling. Scout for armyworm.','orange',29],",
    "      ['Grain Fill','Jul 16 - Aug 15','Reduce irrigation. Stop nitrogen. Monitor for ear rots.','amber',31],",
    "      ['Harvest','Aug 16 - Sep 15','Harvest at 20-25% moisture. Dry to 13% before storage. Expected: 2.0-3.0 t/acre.','green',30],",
    "    ],",
    "  };",
    "  Color _c(String k) { switch(k) { case 'lime': return AppColors.limeGreen; case 'blue': return AppColors.skyBlue; case 'orange': return AppColors.burntOrange; case 'amber': return AppColors.amber; default: return AppColors.deepGreen; } }",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    final stages = _data[_crop] ?? [];",
    "    return Scaffold(backgroundColor: AppColors.offWhite, body: Column(children: [",
    "      Container(padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 10),",
    "        decoration: BoxDecoration(color: AppColors.cardSurface, border: Border(bottom: BorderSide(color: AppColors.grey200))),",
    "        child: SingleChildScrollView(scrollDirection: Axis.horizontal, child: Row(children: [",
    "          Text('Crop Calendar', style: AppTextStyles.headingMedium),",
    "          const SizedBox(width: 24),",
    "          ...AppCrops.all.map((c) {",
    "            final sel = _crop == c['id'];",
    "            return Padding(padding: const EdgeInsets.only(right: 8), child: FilterChip(",
    "              label: Text(c['label']!), selected: sel,",
    "              onSelected: (_) => setState(() => _crop = c['id']!),",
    "              selectedColor: AppColors.deepGreen, checkmarkColor: Colors.white,",
    "              labelStyle: TextStyle(color: sel ? Colors.white : AppColors.darkText, fontSize: 13),",
    "              backgroundColor: AppColors.grey100, side: BorderSide.none));",
    "          }),",
    "        ]))),",
    "      Expanded(child: SingleChildScrollView(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        Container(width: double.infinity, padding: const EdgeInsets.all(16),",
    "          decoration: BoxDecoration(color: AppColors.deepGreen, borderRadius: BorderRadius.circular(12)),",
    "          child: Row(children: [",
    "            const Icon(Icons.calendar_month_rounded, color: Colors.white, size: 32),",
    "            const SizedBox(width: 16),",
    "            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "              Text(AppCrops.all.firstWhere((c) => c['id'] == _crop)['label']! + ' Growing Calendar',",
    "                style: AppTextStyles.headingSmall.copyWith(color: Colors.white)),",
    "              const SizedBox(height: 4),",
    "              Text('Tap any stage card for detailed instructions',",
    "                style: AppTextStyles.bodySmall.copyWith(color: Colors.white70)),",
    "            ])),",
    "          ])),",
    "        const SizedBox(height: 24),",
    "        Text('Growing Stages', style: AppTextStyles.headingMedium),",
    "        const SizedBox(height: 16),",
    "        ...stages.asMap().entries.map((e) {",
    "          final i = e.key; final s = e.value; final color = _c(s[3] as String);",
    "          return Padding(padding: const EdgeInsets.only(bottom: 0),",
    "            child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "              SizedBox(width: 60, child: Column(children: [",
    "                Container(width: 44, height: 44,",
    "                  decoration: BoxDecoration(color: color.withValues(alpha: 0.12), shape: BoxShape.circle, border: Border.all(color: color, width: 2)),",
    "                  child: Icon(Icons.agriculture_rounded, color: color, size: 20)),",
    "                if (i < stages.length - 1) Expanded(child: Container(width: 2,",
    "                  margin: const EdgeInsets.symmetric(vertical: 4), color: color.withValues(alpha: 0.3))),",
    "              ])),",
    "              Expanded(child: Padding(padding: const EdgeInsets.only(left: 12, bottom: 24),",
    "                child: _SC(name: s[0] as String, dates: s[1] as String,",
    "                  instructions: s[2] as String, color: color, days: s[4] as int))),",
    "            ]))).animate(delay: Duration(milliseconds: i * 80)).fadeIn(duration: 400.ms).slideX(begin: 0.1, end: 0);",
    "        }),",
    "      ]))),",
    "    ]));",
    "  }",
    "}",
    "class _SC extends StatefulWidget {",
    "  final String name, dates, instructions;",
    "  final Color color; final int days;",
    "  const _SC({required this.name, required this.dates, required this.instructions, required this.color, required this.days});",
    "  @override State<_SC> createState() => _SCS();",
    "}",
    "class _SCS extends State<_SC> {",
    "  bool _open = false;",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return GestureDetector(onTap: () => setState(() => _open = !_open),",
    "      child: AnimatedContainer(duration: const Duration(milliseconds: 220),",
    "        decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
    "          border: Border.all(color: _open ? widget.color : AppColors.grey200, width: _open ? 2 : 1),",
    "          boxShadow: AppShadows.card),",
    "        padding: const EdgeInsets.all(14),",
    "        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "          Row(children: [",
    "            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "              Text(widget.name, style: AppTextStyles.headingSmall.copyWith(fontSize: 14)),",
    "              const SizedBox(height: 2),",
    "              Row(children: [",
    "                Icon(Icons.calendar_today_rounded, size: 12, color: widget.color),",
    "                const SizedBox(width: 4),",
    "                Text(widget.dates, style: TextStyle(fontSize: 12, color: widget.color, fontWeight: FontWeight.w600)),",
    "                const SizedBox(width: 12),",
    "                Icon(Icons.schedule_rounded, size: 12, color: AppColors.grey600),",
    "                const SizedBox(width: 4),",
    "                Text(widget.days.toString() + ' days', style: AppTextStyles.bodySmall),",
    "              ]),",
    "            ])),",
    "            Icon(_open ? Icons.keyboard_arrow_up_rounded : Icons.keyboard_arrow_down_rounded, color: AppColors.grey600),",
    "          ]),",
    "          if (_open) ...[",
    "            const SizedBox(height: 10), const Divider(height: 1), const SizedBox(height: 10),",
    "            Text(widget.instructions, style: AppTextStyles.bodyMedium.copyWith(height: 1.6)),",
    "          ],",
    "        ]),",
    "      ),",
    "    );",
    "  }",
    "}",
])

# ── reports_screen.dart ───────────────────────────────────────────────
write('lib' + bs + 'screens' + bs + 'reports' + bs + 'reports_screen.dart', [
    "import 'package:flutter/material.dart';",
    "import 'package:flutter_riverpod/flutter_riverpod.dart';",
    "import 'package:pdf/pdf.dart';",
    "import 'package:pdf/widgets.dart' as pw;",
    "import 'package:printing/printing.dart';",
    "import 'package:cropsense/core/theme.dart';",
    "import 'package:cropsense/core/constants.dart';",
    "class ReportsScreen extends ConsumerStatefulWidget {",
    "  const ReportsScreen({super.key});",
    "  @override",
    "  ConsumerState<ReportsScreen> createState() => _State();",
    "}",
    "class _State extends ConsumerState<ReportsScreen> {",
    "  String _district = 'faisalabad'; String _crop = 'wheat'; bool _busy = false;",
    "  @override",
    "  Widget build(BuildContext context) {",
    "    return Scaffold(backgroundColor: AppColors.offWhite,",
    "      body: SingleChildScrollView(padding: const EdgeInsets.all(24),",
    "        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "          Text('Reports', style: AppTextStyles.displayLarge),",
    "          const SizedBox(height: 4),",
    "          Text('Generate PDF reports for government, insurance, and NGO clients',",
    "            style: AppTextStyles.bodyMedium.copyWith(color: AppColors.grey600)),",
    "          const SizedBox(height: 32),",
    "          _card('District Intelligence Report',",
    "            'Yield forecast, risk assessment, AI recommendations and cost/ROI in PKR.',",
    "            Icons.location_on_rounded, AppColors.deepGreen,",
    "            ['Government', 'District Level', 'AI Advisory'], _sel(), _districtReport),",
    "          const SizedBox(height: 16),",
    "          _card('National Risk Summary',",
    "            'Province-by-province breakdown across all 36 districts. For MNFSR briefings.',",
    "            Icons.map_rounded, AppColors.skyBlue,",
    "            ['MNFSR', 'National Level', 'All Districts'], null, _nationalReport),",
    "          const SizedBox(height: 16),",
    "          _card('Farmer Advisory Sheet',",
    "            'One-page advice in Roman Urdu. What to spray, cost per acre. Printable.',",
    "            Icons.person_rounded, AppColors.limeGreen,",
    "            ['Farmers', 'Roman Urdu', 'Printable'], _sel(), _farmerReport),",
    "        ])));",
    "  }",
    "  Widget _sel() => Row(children: [",
    "    Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "      Text('District', style: AppTextStyles.label),",
    "      DropdownButton<String>(value: _district, isExpanded: true, underline: const SizedBox.shrink(),",
    "        items: AppDistricts.all.take(12).map((d) => DropdownMenuItem(value: d['id'], child: Text(d['label']!))).toList(),",
    "        onChanged: (v) => setState(() => _district = v!)),",
    "    ])),",
    "    const SizedBox(width: 16),",
    "    Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "      Text('Crop', style: AppTextStyles.label),",
    "      DropdownButton<String>(value: _crop, isExpanded: true, underline: const SizedBox.shrink(),",
    "        items: AppCrops.all.map((c) => DropdownMenuItem(value: c['id'], child: Text(c['label']!))).toList(),",
    "        onChanged: (v) => setState(() => _crop = v!)),",
    "    ])),",
    "  ]);",
    "  Widget _card(String title, String desc, IconData icon, Color color, List<String> tags, Widget? extra, VoidCallback onTap) {",
    "    return Container(",
    "      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12),",
    "        border: Border.all(color: AppColors.grey200), boxShadow: AppShadows.card),",
    "      padding: const EdgeInsets.all(20),",
    "      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "        Row(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "          Container(padding: const EdgeInsets.all(12),",
    "            decoration: BoxDecoration(color: color.withValues(alpha: 0.12), borderRadius: BorderRadius.circular(12)),",
    "            child: Icon(icon, color: color, size: 28)),",
    "          const SizedBox(width: 16),",
    "          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [",
    "            Text(title, style: AppTextStyles.headingSmall),",
    "            const SizedBox(height: 6),",
    "            Text(desc, style: AppTextStyles.bodySmall.copyWith(height: 1.6, color: AppColors.grey600)),",
    "            const SizedBox(height: 8),",
    "            Wrap(spacing: 6, children: tags.map((t) => Container(",
    "              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),",
    "              decoration: BoxDecoration(color: color.withValues(alpha: 0.08),",
    "                borderRadius: BorderRadius.circular(100), border: Border.all(color: color.withValues(alpha: 0.3))),",
    "              child: Text(t, style: TextStyle(fontSize: 11, color: color, fontWeight: FontWeight.w600)),",
    "            )).toList()),",
    "          ])),",
    "        ]),",
    "        if (extra != null) ...[const SizedBox(height: 14), const Divider(), const SizedBox(height: 10), extra],",
    "        const SizedBox(height: 16),",
    "        Row(children: [const Spacer(),",
    "          ElevatedButton.icon(",
    "            onPressed: _busy ? null : onTap,",
    "            icon: _busy ? const SizedBox(width: 16, height: 16,",
    "              child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))",
    "              : const Icon(Icons.picture_as_pdf_rounded, size: 16),",
    "            label: Text(_busy ? 'Generating...' : 'Download PDF'),",
    "            style: ElevatedButton.styleFrom(backgroundColor: color, foregroundColor: Colors.white)),",
    "        ]),",
    "      ]),",
    "    );",
    "  }",
    "  pw.Widget _cell(String t, {bool b = false, bool w = false}) => pw.Padding(",
    "    padding: const pw.EdgeInsets.all(6),",
    "    child: pw.Text(t, style: pw.TextStyle(fontSize: 9,",
    "      fontWeight: b ? pw.FontWeight.bold : pw.FontWeight.normal,",
    "      color: w ? PdfColors.white : PdfColors.black)));",
    "  Future<void> _districtReport() async {",
    "    setState(() => _busy = true);",
    "    try {",
    "      final dl = AppDistricts.all.firstWhere((d) => d['id'] == _district)['label']!;",
    "      final cl = AppCrops.all.firstWhere((c) => c['id'] == _crop)['label']!;",
    "      final pdf = pw.Document();",
    "      pdf.addPage(pw.MultiPage(pageFormat: PdfPageFormat.a4, margin: const pw.EdgeInsets.all(40), build: (ctx) => [",
    "        pw.Container(width: double.infinity, padding: const pw.EdgeInsets.all(16),",
    "          decoration: pw.BoxDecoration(color: PdfColor.fromHex('1B5E20'), borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8))),",
    "          child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [",
    "            pw.Text('CropSense District Intelligence Report', style: pw.TextStyle(color: PdfColors.white, fontSize: 18, fontWeight: pw.FontWeight.bold)),",
    "            pw.Text(dl + ' - ' + cl + ' - Pakistan', style: const pw.TextStyle(color: PdfColors.white, fontSize: 12)),",
    "          ])),",
    "        pw.SizedBox(height: 20),",
    "        pw.Text('Field Conditions', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('1B5E20'))),",
    "        pw.SizedBox(height: 8),",
    "        pw.Table(border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5), children: [",
    "          pw.TableRow(decoration: pw.BoxDecoration(color: PdfColor.fromHex('1B5E20')), children: [_cell('Indicator', b: true, w: true), _cell('Value', b: true, w: true), _cell('Status', b: true, w: true)]),",
    "          pw.TableRow(children: [_cell('NDVI'), _cell('0.62'), _cell('Moderate')]),",
    "          pw.TableRow(decoration: const pw.BoxDecoration(color: PdfColors.grey100), children: [_cell('Yield Forecast'), _cell('2.3 t/acre'), _cell('Near average')]),",
    "          pw.TableRow(children: [_cell('Risk Score'), _cell('35/100'), _cell('WATCH')]),",
    "          pw.TableRow(decoration: const pw.BoxDecoration(color: PdfColors.grey100), children: [_cell('Rainfall'), _cell('82mm'), _cell('Below average')]),",
    "          pw.TableRow(children: [_cell('Max Temp'), _cell('38 C'), _cell('Elevated')]),",
    "        ]),",
    "        pw.SizedBox(height: 16),",
    "        pw.Text('AI Advisory', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('1B5E20'))),",
    "        pw.SizedBox(height: 8),",
    "        pw.Text('Roman Urdu: Fasal ko zang ka khatara hai - subah spray karein',",
    "          style: pw.TextStyle(fontSize: 11, fontStyle: pw.FontStyle.italic, color: PdfColor.fromHex('B71C1C'))),",
    "        pw.SizedBox(height: 8),",
    "        ...['1. Apply Topsin-M 70WP at 250g/acre within 48 hours', '2. Irrigate every 8 days', '3. Hold Urea for 2 weeks', '4. Monitor daily']",
    "          .map((s) => pw.Padding(padding: const pw.EdgeInsets.only(bottom: 4), child: pw.Text(s, style: const pw.TextStyle(fontSize: 10)))),",
    "        pw.SizedBox(height: 16),",
    "        pw.Text('Cost and ROI', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('1B5E20'))),",
    "        pw.SizedBox(height: 8),",
    "        pw.Table(border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5), children: [",
    "          pw.TableRow(decoration: pw.BoxDecoration(color: PdfColor.fromHex('1B5E20')), children: [_cell('Item', b: true, w: true), _cell('Amount', b: true, w: true)]),",
    "          pw.TableRow(children: [_cell('Treatment/acre'), _cell('Rs. 12,500')]),",
    "          pw.TableRow(decoration: const pw.BoxDecoration(color: PdfColors.grey100), children: [_cell('Protected yield'), _cell('Rs. 45,000')]),",
    "          pw.TableRow(children: [_cell('ROI', b: true), _cell('260%', b: true)]),",
    "        ]),",
    "      ]));",
    "      await Printing.layoutPdf(onLayout: (_) => pdf.save(), name: 'CropSense_' + dl + '_' + cl + '.pdf');",
    "    } finally { setState(() => _busy = false); }",
    "  }",
    "  Future<void> _nationalReport() async {",
    "    setState(() => _busy = true);",
    "    try {",
    "      final pdf = pw.Document();",
    "      pdf.addPage(pw.Page(pageFormat: PdfPageFormat.a4, margin: const pw.EdgeInsets.all(40),",
    "        build: (ctx) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [",
    "          pw.Container(width: double.infinity, padding: const pw.EdgeInsets.all(16), color: PdfColor.fromHex('1B5E20'),",
    "            child: pw.Text('CropSense National Crop Risk Summary', style: pw.TextStyle(color: PdfColors.white, fontSize: 18, fontWeight: pw.FontWeight.bold))),",
    "          pw.SizedBox(height: 20),",
    "          pw.Text('Province Overview', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),",
    "          pw.SizedBox(height: 8),",
    "          pw.Table(border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5), children: [",
    "            pw.TableRow(decoration: pw.BoxDecoration(color: PdfColor.fromHex('1B5E20')), children: [_cell('Province', b: true, w: true), _cell('Avg Yield', b: true, w: true), _cell('NDVI', b: true, w: true), _cell('Risk', b: true, w: true)]),",
    "            pw.TableRow(children: [_cell('Punjab'), _cell('2.4 t/ac'), _cell('0.64'), _cell('WATCH')]),",
    "            pw.TableRow(decoration: const pw.BoxDecoration(color: PdfColors.grey100), children: [_cell('Sindh'), _cell('1.9 t/ac'), _cell('0.51'), _cell('HIGH')]),",
    "            pw.TableRow(children: [_cell('Khyber Pakhtunkhwa'), _cell('2.1 t/ac'), _cell('0.68'), _cell('ABOVE AVG')]),",
    "            pw.TableRow(decoration: const pw.BoxDecoration(color: PdfColors.grey100), children: [_cell('Balochistan'), _cell('1.2 t/ac'), _cell('0.31'), _cell('CRITICAL')]),",
    "          ]),",
    "        ])));",
    "      await Printing.layoutPdf(onLayout: (_) => pdf.save(), name: 'CropSense_National.pdf');",
    "    } finally { setState(() => _busy = false); }",
    "  }",
    "  Future<void> _farmerReport() async {",
    "    setState(() => _busy = true);",
    "    try {",
    "      final dl = AppDistricts.all.firstWhere((d) => d['id'] == _district)['label']!;",
    "      final pdf = pw.Document();",
    "      pdf.addPage(pw.Page(pageFormat: PdfPageFormat.a4, margin: const pw.EdgeInsets.all(30),",
    "        build: (ctx) => pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [",
    "          pw.Container(width: double.infinity, padding: const pw.EdgeInsets.all(12), color: PdfColor.fromHex('1B5E20'),",
    "            child: pw.Text('CropSense - Kisan Advisory Sheet - ' + dl,",
    "              style: pw.TextStyle(color: PdfColors.white, fontSize: 16, fontWeight: pw.FontWeight.bold))),",
    "          pw.SizedBox(height: 16),",
    "          pw.Text('Fasal ki Halat (Field Conditions)', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),",
    "          pw.SizedBox(height: 6),",
    "          pw.Text('Aapki fasal mein zang ka khatara hai. Neeche di gayi hidayaat par amal karein.', style: const pw.TextStyle(fontSize: 11)),",
    "          pw.SizedBox(height: 12),",
    "          pw.Text('Kya Karein?', style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('1B5E20'))),",
    "          pw.SizedBox(height: 6),",
    "          ...['1. Topsin-M 70WP spray karein - 250g per acre', '2. Pani 8 din baad dein', '3. 2 hafte Urea na daalein']",
    "            .map((s) => pw.Padding(padding: const pw.EdgeInsets.only(bottom: 5), child: pw.Text(s, style: const pw.TextStyle(fontSize: 11)))),",
    "          pw.SizedBox(height: 12),",
    "          pw.Table(border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5), children: [",
    "            pw.TableRow(decoration: pw.BoxDecoration(color: PdfColor.fromHex('8BC34A')), children: [_cell('Cheez', b: true, w: true), _cell('Miqdar', b: true, w: true), _cell('Qeemat', b: true, w: true)]),",
    "            pw.TableRow(children: [_cell('Topsin-M'), _cell('250g/acre'), _cell('Rs. 850')]),",
    "            pw.TableRow(decoration: const pw.BoxDecoration(color: PdfColors.grey100), children: [_cell('Dithane M-45'), _cell('500g/acre'), _cell('Rs. 650')]),",
    "          ]),",
    "        ])));",
    "      await Printing.layoutPdf(onLayout: (_) => pdf.save(), name: 'Kisan_' + dl + '.pdf');",
    "    } finally { setState(() => _busy = false); }",
    "  }",
    "}",
])

print('\nALL FILES WRITTEN SUCCESSFULLY!')